### ISSUE TITLE
Determine which server-side framework to be using

### ISSUE THREAD

**Issue by hexacyanide** [pjuapps/server#1]
Please review a framework from [framework-examples](https://github.com/pjuapps/framework-examples) and provide feedback on which framework you would like to be using. Selection is to be complete by 12/05. The current sentiment appears to be leaning towards the use of Node.js and Express.

The current options are Django or Flask (which are written in Python), and Express (which is written in server-side JavaScript).

**Comment by shanesarnac** [comment]
I believe that the Node.js and Express option is the best for a couple of reasons:
1. Some people already have experience with it
2. Since we'll be working with a lot of Javascript for the client-side, I think it will simplify things to use the framework that uses Javascript, minimizing the number of languages we'd have to manage.
Finally, Express seems to be a pretty common, well-documented option so I have no problems using it beyond my relative lack of experience in Javascript relative to Python.

**Comment by faka3118** [comment]
After doing some reading on the internet, I agree with Shane. I chose Express framework for some reason:

* we can use a single language for both frontend & backend.

I have a limited knowledge and experience in Javascript apart from what I've learned in the PPL class, therefore I have started learning it again independently.

**Comment by ehka** [comment]
Express sounds good!

**Comment by hexacyanide** [comment]
It appears we will be using Node.js and Express for this project. I will create the initial code skeleton in this repository and remove the framework-examples repository at a later time.

Please ensure that you have an LTS version of Node.js installed, with a working package manager (NPM). The most recent LTS is v8.9.2, and the package manager should be around version 5. Please inform me if you have any problems with installation.
